#!/usr/bin/env python3
"""Orze CLI — GPU experiment orchestrator.

Usage:
    python -m orze.cli                          # all GPUs, continuous
    python -m orze.cli -c orze.yaml --gpus 0,1  # with project config
    python -m orze.cli --once                   # one cycle then exit
    python -m orze.cli --report-only            # regenerate report
    python -m orze.cli --init                   # initialize new project
    python -m orze.cli --admin                  # launch admin panel
"""

import argparse
import logging
import os
import sys
from pathlib import Path

from orze import __version__
from orze.core.config import load_project_config
from orze.hardware.gpu import detect_all_gpus

logger = logging.getLogger("orze")

# ---------------------------------------------------------------------------
# Template for --init scaffolding
# ---------------------------------------------------------------------------

BASELINE_TRAIN_PY = '''\
#!/usr/bin/env python3
"""Baseline training script generated by orze --init.

Replace this with your real training script. Orze will call it as:
    python train.py --idea_config <path_to_yaml>
"""
import argparse
import json
import sys
import time
from pathlib import Path

import yaml


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--idea_config", required=True, help="Path to idea config YAML")
    args = parser.parse_args()

    cfg = yaml.safe_load(Path(args.idea_config).read_text())
    print(f"Training with config: {cfg}")

    # --- Replace with your training logic ---
    time.sleep(2)
    accuracy = 0.5
    loss = 1.0
    # -----------------------------------------

    # Write metrics (orze reads this to track results)
    metrics = {
        "status": "COMPLETED",
        "test_accuracy": accuracy,
        "test_loss": loss,
        "training_time": 2.0,
    }
    idea_dir = Path(args.idea_config).parent
    (idea_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))
    print(f"Done. Metrics: {metrics}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def setup_logging(verbose: bool = False):
    """Configure logging with timestamps."""
    level = logging.DEBUG if verbose else logging.INFO
    fmt = "%(asctime)s [%(levelname)s] %(message)s"
    datefmt = "%Y-%m-%d %H:%M:%S"
    logging.basicConfig(level=level, format=fmt, datefmt=datefmt)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="orze: GPU experiment orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python -m orze.cli                             # all GPUs, continuous
  python -m orze.cli -c orze.yaml --gpus 0,1     # with project config
  python -m orze.cli --once                      # one cycle then exit
  python -m orze.cli --report-only               # regenerate report
        """,
    )
    parser.add_argument("-V", "--version", action="version",
                        version=f"orze {__version__}")
    parser.add_argument("-c", "--config-file", type=str, default=None,
                        help="Path to orze.yaml project config")
    parser.add_argument("--gpus", type=str, default=None,
                        help="Comma-separated GPU IDs (default: auto-detect)")
    parser.add_argument("--timeout", type=int, default=None,
                        help="Max training time in seconds")
    parser.add_argument("--poll", type=int, default=None,
                        help="Seconds between iterations")
    parser.add_argument("--once", action="store_true",
                        help="Run one cycle and exit")
    parser.add_argument("--stop", action="store_true",
                        help="Gracefully stop a running orze instance")
    parser.add_argument("--disable", action="store_true",
                        help="Stop and persistently disable Orze (survives restarts)")
    parser.add_argument("--enable", action="store_true",
                        help="Remove persistent disable flag to allow Orze to run")
    parser.add_argument("--report-only", action="store_true",
                        help="Only regenerate report")
    parser.add_argument("--role-only", type=str, default=None, metavar="NAME",
                        help="Run a single agent role once and exit")
    parser.add_argument("--research-only", action="store_true",
                        help="Alias for --role-only research")
    parser.add_argument("--ideas-md", type=str, default=None,
                        help="Path to ideas markdown file")
    parser.add_argument("--base-config", type=str, default=None,
                        help="Path to base config YAML")
    parser.add_argument("--results-dir", type=str, default=None,
                        help="Directory for results")
    parser.add_argument("--train-script", type=str, default=None,
                        help="Training script to run per idea")
    parser.add_argument("--init", action="store_true",
                        help="Initialize a new orze project in the current directory")
    parser.add_argument("--admin", action="store_true",
                        help="Launch admin panel instead of farm loop")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Debug logging")
    args = parser.parse_args()

    setup_logging(args.verbose)

    # Load project config, then apply CLI overrides
    cfg = load_project_config(args.config_file)
    cfg["_config_path"] = args.config_file or "orze.yaml"  # stored for mode: research

    # --admin: launch web panel
    if args.admin:
        from orze.admin.server import run_admin
        run_admin(cfg)
        return

    # --init: initialize a new project in the current directory
    if args.init:
        print("\n\033[1mOrze — Initialization\033[0m")
        print("---------------------")

        # 1. Detect project type
        py_files = list(Path(".").rglob("*.py"))
        is_torch = any("torch" in f.read_text(errors="ignore") for f in py_files[:20])
        print(f"Project context: {'PyTorch' if is_torch else 'Generic ML'}")

        # 2. Find/create training script
        train_scripts = []
        for p in Path(".").glob("**/train*.py"):
            if "orze" in str(p):
                continue
            train_scripts.append(str(p))

        train_script = None
        if train_scripts:
            train_script = train_scripts[0]
            print(f"Detected training script: {train_script}")
        else:
            train_script = "train.py"
            if not Path(train_script).exists():
                print(f"No training script found. Creating {train_script}...")
                Path(train_script).write_text(BASELINE_TRAIN_PY.strip() + "\n", encoding="utf-8")
            else:
                print(f"Using existing {train_script}")

        # 3. Create orze.yaml
        if not Path("orze.yaml").exists():
            print("Creating orze.yaml...")
            backend = ("anthropic" if os.environ.get("ANTHROPIC_API_KEY") else
                       "gemini" if os.environ.get("GEMINI_API_KEY") else
                       "openai" if os.environ.get("OPENAI_API_KEY") else "ollama")

            yaml_content = f"""# orze.yaml — Project configuration
train_script: {train_script}
ideas_file: ideas.md
results_dir: results
python: {sys.executable}

# Research agent settings (optional)
# roles:
#   research:
#     mode: research
#     backend: {backend}
#     cooldown: 600
#     timeout: 300
"""
            Path("orze.yaml").write_text(yaml_content, encoding="utf-8")
        else:
            print("orze.yaml already exists — skipping")

        # 4. Create ideas.md
        if not Path("ideas.md").exists():
            print("Creating ideas.md...")
            Path("ideas.md").write_text(
                "# Ideas\n\n"
                "## idea-0001: Baseline\n"
                "- **Priority**: high\n\n"
                "```yaml\n"
                "learning_rate: 0.001\n"
                "epochs: 10\n"
                "```\n",
                encoding="utf-8",
            )
        else:
            print("ideas.md already exists — skipping")

        # 5. Create results directory
        Path("results").mkdir(exist_ok=True)

        print("\nDone! Run `python -m orze.cli` to start.")
        return

    # Apply CLI overrides
    if args.timeout is not None:
        cfg["timeout"] = args.timeout
    if args.poll is not None:
        cfg["poll"] = args.poll
    if args.ideas_md:
        cfg["ideas_file"] = args.ideas_md
    if args.base_config:
        cfg["base_config"] = args.base_config
    if args.results_dir:
        cfg["results_dir"] = args.results_dir
    if args.train_script:
        cfg["train_script"] = args.train_script

    # --stop
    if args.stop:
        import datetime
        from orze.core.fs import atomic_write
        stop_path = Path(cfg["results_dir"]) / ".orze_stop_all"
        atomic_write(stop_path, datetime.datetime.now().isoformat())
        print(f"Stop sentinel written to {stop_path}")
        return

    # --disable
    if args.disable:
        import datetime
        from orze.core.fs import atomic_write
        disable_path = Path(cfg["results_dir"]) / ".orze_disabled"
        atomic_write(disable_path, f"Disabled at {datetime.datetime.now().isoformat()}")
        print(f"Orze disabled. Remove {disable_path} to re-enable.")
        return

    # --enable
    if args.enable:
        disable_path = Path(cfg["results_dir"]) / ".orze_disabled"
        if disable_path.exists():
            disable_path.unlink()
            print("Orze re-enabled.")
        else:
            print("Orze was not disabled.")
        return

    # --report-only
    if args.report_only:
        from orze.core.ideas import parse_ideas
        from orze.reporting.leaderboard import update_report
        ideas = parse_ideas(cfg["ideas_file"])
        results_dir = Path(cfg["results_dir"])
        lake = None
        lake_path = Path(cfg["ideas_file"]).parent / "idea_lake.db"
        if lake_path.exists():
            from orze.idea_lake import IdeaLake
            lake = IdeaLake(str(lake_path))
        update_report(results_dir, ideas, cfg, lake=lake)
        print("Report updated.")
        return

    # --research-only is an alias for --role-only research
    if args.research_only:
        args.role_only = "research"

    # Detect GPUs
    if args.gpus:
        gpu_ids = [int(g.strip()) for g in args.gpus.split(",")]
    else:
        gpu_ids = detect_all_gpus()

    if not gpu_ids:
        logger.error("No GPUs detected. Use --gpus to specify manually.")
        sys.exit(1)

    # Launch orchestrator
    from orze.engine.orchestrator import Orze
    orze = Orze(gpu_ids, cfg, once=args.once)

    if args.role_only:
        orze._run_role_once(args.role_only)
    else:
        orze.run()


if __name__ == "__main__":
    main()
