#!/usr/bin/env python3
"""Orze CLI — GPU experiment orchestrator.

Usage:
    python -m orze.cli                          # all GPUs, continuous
    python -m orze.cli -c orze.yaml --gpus 0,1  # with project config
    python -m orze.cli --once                   # one cycle then exit
    python -m orze.cli --report-only            # regenerate report
    python -m orze.cli --init                   # initialize new project
    python -m orze.cli --admin                  # launch admin panel
"""

import argparse
import logging
import os
import sys
from pathlib import Path

from orze import __version__
from orze.core.config import load_project_config
from orze.hardware.gpu import detect_all_gpus

logger = logging.getLogger("orze")

# ---------------------------------------------------------------------------
# Template for --init scaffolding
# ---------------------------------------------------------------------------

BASELINE_TRAIN_PY = '''\
#!/usr/bin/env python3
"""Baseline training script generated by orze --init.

Replace this with your real training script. Orze will call it as:
    python train.py --idea_config <path_to_yaml>
"""
import argparse
import json
import sys
import time
from pathlib import Path

import yaml


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--idea_config", required=True, help="Path to idea config YAML")
    args = parser.parse_args()

    cfg = yaml.safe_load(Path(args.idea_config).read_text())
    print(f"Training with config: {cfg}")

    # --- Replace with your training logic ---
    time.sleep(2)
    accuracy = 0.5
    loss = 1.0
    # -----------------------------------------

    # Write metrics (orze reads this to track results)
    metrics = {
        "status": "COMPLETED",
        "test_accuracy": accuracy,
        "test_loss": loss,
        "training_time": 2.0,
    }
    idea_dir = Path(args.idea_config).parent
    (idea_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))
    print(f"Done. Metrics: {metrics}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def setup_logging(verbose: bool = False):
    """Configure logging with timestamps."""
    level = logging.DEBUG if verbose else logging.INFO
    fmt = "%(asctime)s [%(levelname)s] %(message)s"
    datefmt = "%Y-%m-%d %H:%M:%S"
    logging.basicConfig(level=level, format=fmt, datefmt=datefmt)


# ---------------------------------------------------------------------------
# Uninstall
# ---------------------------------------------------------------------------

# Files inside each idea dir to keep (research results)
_IDEA_KEEP = {
    "metrics.json",
    "eval_report.json",
    "eval_output.log",
}

# Top-level results_dir files to keep
_RESULTS_KEEP = {"report.md", "status.json"}


def _do_uninstall(cfg: dict):
    """Full uninstall: stop orze, strip runtime files, pip uninstall.

    Preserves research results:
        - results/{idea-*}/metrics.json  (core experiment data)
        - results/{idea-*}/eval_report.json, eval_output.log
        - results/report.md, status.json
        - ideas.md, idea_lake.db
    """
    import shutil
    import subprocess

    results_dir = Path(cfg["results_dir"])
    print("\n\033[1mOrze — Uninstall\033[0m")
    print("-----------------")
    print(f"Results dir : {results_dir.resolve()}")
    print(f"Config      : {cfg.get('_config_path', 'orze.yaml')}")
    print()

    # --- 1. Stop running instances -----------------------------------
    print("[1/4] Stopping running orze instances...")
    stop_path = results_dir / ".orze_stop_all"
    if results_dir.exists():
        stop_path.write_text("uninstall", encoding="utf-8")
        # Also send SIGTERM to any PID files we find
        for pid_file in results_dir.glob(".orze.pid*"):
            try:
                pid = int(pid_file.read_text(encoding="utf-8").strip())
                os.kill(pid, 15)  # SIGTERM
                print(f"  Sent SIGTERM to PID {pid}")
            except (ValueError, ProcessLookupError, PermissionError, OSError):
                pass
    import time
    time.sleep(2)  # give processes a moment to exit

    # --- 2. Clean results directory ----------------------------------
    print("[2/4] Cleaning runtime files from results/...")
    removed = 0
    if results_dir.exists():
        # Remove orze system files (dot-files and underscore-prefixed)
        for p in sorted(results_dir.iterdir()):
            name = p.name
            # Keep the report/status summaries
            if name in _RESULTS_KEEP:
                continue
            # System dot-files (.orze_*, .orze.pid*)
            if name.startswith(".orze"):
                p.unlink(missing_ok=True)
                removed += 1
                continue
            # Underscore-prefixed system files/dirs (_leaderboard.json,
            # _results_cache.json, _host_*.json, _*_lock/, _*_logs/, etc.)
            if name.startswith("_"):
                if p.is_dir():
                    shutil.rmtree(p, ignore_errors=True)
                else:
                    p.unlink(missing_ok=True)
                removed += 1
                continue
            # Log files at top level (orze.log, bug_fixer.log, etc.)
            if name.endswith(".log"):
                p.unlink(missing_ok=True)
                removed += 1
                continue
            # Idea directories — strip everything except research results
            if p.is_dir():
                for child in sorted(p.iterdir()):
                    if child.name in _IDEA_KEEP:
                        continue
                    # Keep subdirectories produced by eval/post-scripts
                    # (overlays/, checkpoints user explicitly asked to keep, etc.)
                    if child.is_dir():
                        continue
                    child.unlink(missing_ok=True)
                    removed += 1

        # Remove empty idea dirs (no metrics.json means no results)
        for p in sorted(results_dir.iterdir()):
            if p.is_dir() and not any(p.iterdir()):
                p.rmdir()
                removed += 1

    print(f"  Removed {removed} runtime file(s)")

    # --- 3. Remove orze config file ----------------------------------
    print("[3/4] Removing orze config...")
    config_path = Path(cfg.get("_config_path", "orze.yaml"))
    if config_path.exists():
        config_path.unlink()
        print(f"  Removed {config_path}")
    else:
        print("  No config file found")

    # --- 4. Pip uninstall --------------------------------------------
    print("[4/4] Uninstalling orze package...")
    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "uninstall", "orze", "-y"],
            check=True,
        )
        print("  orze package removed")
    except subprocess.CalledProcessError:
        print("  WARNING: pip uninstall failed — you may need to run manually:")
        print("    pip uninstall orze")

    # --- Summary -----------------------------------------------------
    print()
    print("\033[1mUninstall complete.\033[0m")
    print("Preserved research results:")
    if results_dir.exists():
        kept = list(results_dir.rglob("metrics.json"))
        print(f"  {len(kept)} experiment result(s) in {results_dir}/")
    ideas_file = Path(cfg.get("ideas_file", "ideas.md"))
    if ideas_file.exists():
        print(f"  {ideas_file} (experiment definitions)")
    lake_path = ideas_file.parent / "idea_lake.db"
    if lake_path.exists():
        print(f"  {lake_path} (idea archive database)")


def _do_upgrade():
    """Upgrade orze to the latest version from PyPI."""
    import subprocess

    print(f"\n\033[1mOrze — Upgrade\033[0m")
    print("---------------")
    print(f"Current version: {__version__}")
    print("Upgrading via pip...\n")

    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--upgrade", "orze"],
            check=True,
        )
    except subprocess.CalledProcessError:
        print("\n\033[31mUpgrade failed.\033[0m Try manually:")
        print("  pip install --upgrade orze")
        return

    # Report the new version
    result = subprocess.run(
        [sys.executable, "-c", "from orze import __version__; print(__version__)"],
        capture_output=True, text=True,
    )
    new_ver = result.stdout.strip() if result.returncode == 0 else "unknown"
    if new_ver == __version__:
        print(f"\nAlready up-to-date (v{__version__}).")
    else:
        print(f"\n\033[32mUpgraded: v{__version__} -> v{new_ver}\033[0m")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="orze: GPU experiment orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python -m orze.cli                             # all GPUs, continuous
  python -m orze.cli -c orze.yaml --gpus 0,1     # with project config
  python -m orze.cli --once                      # one cycle then exit
  python -m orze.cli --report-only               # regenerate report
        """,
    )
    parser.add_argument("-V", "--version", action="version",
                        version=f"orze {__version__}")
    parser.add_argument("-c", "--config-file", type=str, default=None,
                        help="Path to orze.yaml project config")
    parser.add_argument("--gpus", type=str, default=None,
                        help="Comma-separated GPU IDs (default: auto-detect)")
    parser.add_argument("--timeout", type=int, default=None,
                        help="Max training time in seconds")
    parser.add_argument("--poll", type=int, default=None,
                        help="Seconds between iterations")
    parser.add_argument("--once", action="store_true",
                        help="Run one cycle and exit")
    parser.add_argument("--stop", action="store_true",
                        help="Gracefully stop a running orze instance")
    parser.add_argument("--disable", action="store_true",
                        help="Stop and persistently disable Orze (survives restarts)")
    parser.add_argument("--enable", action="store_true",
                        help="Remove persistent disable flag to allow Orze to run")
    parser.add_argument("--report-only", action="store_true",
                        help="Only regenerate report")
    parser.add_argument("--role-only", type=str, default=None, metavar="NAME",
                        help="Run a single agent role once and exit")
    parser.add_argument("--research-only", action="store_true",
                        help="Alias for --role-only research")
    parser.add_argument("--ideas-md", type=str, default=None,
                        help="Path to ideas markdown file")
    parser.add_argument("--base-config", type=str, default=None,
                        help="Path to base config YAML")
    parser.add_argument("--results-dir", type=str, default=None,
                        help="Directory for results")
    parser.add_argument("--train-script", type=str, default=None,
                        help="Training script to run per idea")
    parser.add_argument("--init", action="store_true",
                        help="Initialize a new orze project in the current directory")
    parser.add_argument("--admin", action="store_true",
                        help="Launch admin panel instead of farm loop")
    parser.add_argument("--upgrade", action="store_true",
                        help="Upgrade orze to the latest version from PyPI")
    parser.add_argument("--uninstall", action="store_true",
                        help="Full uninstall: stop orze, remove runtime files, "
                             "pip uninstall — keeps only research results")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Debug logging")
    args = parser.parse_args()

    setup_logging(args.verbose)

    # Load project config, then apply CLI overrides
    cfg = load_project_config(args.config_file)
    cfg["_config_path"] = args.config_file or "orze.yaml"  # stored for mode: research

    # --admin: launch web panel
    if args.admin:
        from orze.admin.server import run_admin
        run_admin(cfg)
        return

    # --upgrade: upgrade orze from PyPI
    if args.upgrade:
        _do_upgrade()
        return

    # --uninstall: full cleanup, keep only research results
    if args.uninstall:
        _do_uninstall(cfg)
        return

    # --init: initialize a new project in the current directory
    if args.init:
        print("\n\033[1mOrze — Initialization\033[0m")
        print("---------------------")

        # 1. Detect project type (shallow scan — skip venvs, node_modules, etc.)
        _skip = {"venv", ".venv", "env", ".env", "node_modules", "__pycache__",
                 ".git", ".tox", ".nox", "results", "wandb", ".eggs", "dist", "build"}
        py_files: list[Path] = []
        for entry in Path(".").iterdir():
            if entry.is_file() and entry.suffix == ".py":
                py_files.append(entry)
            elif entry.is_dir() and entry.name not in _skip:
                for child in entry.iterdir():
                    if child.is_file() and child.suffix == ".py":
                        py_files.append(child)
        is_torch = any("torch" in f.read_text(errors="ignore") for f in py_files[:20])
        print(f"Project context: {'PyTorch' if is_torch else 'Generic ML'}")

        # 2. Find/create training script (depth ≤ 2)
        train_scripts = []
        for p in py_files:
            if p.name.startswith("train") and "orze" not in str(p):
                train_scripts.append(str(p))

        train_script = None
        if train_scripts:
            train_script = train_scripts[0]
            print(f"Detected training script: {train_script}")
        else:
            train_script = "train.py"
            if not Path(train_script).exists():
                print(f"No training script found. Creating {train_script}...")
                Path(train_script).write_text(BASELINE_TRAIN_PY.strip() + "\n", encoding="utf-8")
            else:
                print(f"Using existing {train_script}")

        # 3. Create orze.yaml
        if not Path("orze.yaml").exists():
            print("Creating orze.yaml...")
            backend = ("anthropic" if os.environ.get("ANTHROPIC_API_KEY") else
                       "gemini" if os.environ.get("GEMINI_API_KEY") else
                       "openai" if os.environ.get("OPENAI_API_KEY") else "ollama")

            yaml_content = f"""# orze.yaml — Project configuration
train_script: {train_script}
ideas_file: ideas.md
results_dir: results
python: {sys.executable}

# Research agent settings (optional)
# roles:
#   research:
#     mode: research
#     backend: {backend}
#     cooldown: 600
#     timeout: 300
"""
            Path("orze.yaml").write_text(yaml_content, encoding="utf-8")
        else:
            print("orze.yaml already exists — skipping")

        # 4. Create ideas.md
        if not Path("ideas.md").exists():
            print("Creating ideas.md...")
            Path("ideas.md").write_text(
                "# Ideas\n\n"
                "## idea-0001: Baseline\n"
                "- **Priority**: high\n\n"
                "```yaml\n"
                "learning_rate: 0.001\n"
                "epochs: 10\n"
                "```\n",
                encoding="utf-8",
            )
        else:
            print("ideas.md already exists — skipping")

        # 5. Create results directory
        Path("results").mkdir(exist_ok=True)

        print()
        print("\033[32m✔ Initialization complete.\033[0m")
        print()
        print("\033[1mNext steps:\033[0m")
        print("  Claude / Gemini / Codex CLI  →  \033[36m@orze/AGENT.md\033[0m")
        print("  Terminal                     →  \033[36m$ orze\033[0m")
        return

    # Apply CLI overrides
    if args.timeout is not None:
        cfg["timeout"] = args.timeout
    if args.poll is not None:
        cfg["poll"] = args.poll
    if args.ideas_md:
        cfg["ideas_file"] = args.ideas_md
    if args.base_config:
        cfg["base_config"] = args.base_config
    if args.results_dir:
        cfg["results_dir"] = args.results_dir
    if args.train_script:
        cfg["train_script"] = args.train_script

    # --stop
    if args.stop:
        import datetime
        from orze.core.fs import atomic_write
        stop_path = Path(cfg["results_dir"]) / ".orze_stop_all"
        atomic_write(stop_path, datetime.datetime.now().isoformat())
        print(f"Stop sentinel written to {stop_path}")
        return

    # --disable
    if args.disable:
        import datetime
        from orze.core.fs import atomic_write
        disable_path = Path(cfg["results_dir"]) / ".orze_disabled"
        atomic_write(disable_path, f"Disabled at {datetime.datetime.now().isoformat()}")
        print(f"Orze disabled. Remove {disable_path} to re-enable.")
        return

    # --enable
    if args.enable:
        disable_path = Path(cfg["results_dir"]) / ".orze_disabled"
        if disable_path.exists():
            disable_path.unlink()
            print("Orze re-enabled.")
        else:
            print("Orze was not disabled.")
        return

    # --report-only
    if args.report_only:
        from orze.core.ideas import parse_ideas
        from orze.reporting.leaderboard import update_report
        ideas = parse_ideas(cfg["ideas_file"])
        results_dir = Path(cfg["results_dir"])
        lake = None
        lake_path = Path(cfg["ideas_file"]).parent / "idea_lake.db"
        if lake_path.exists():
            from orze.idea_lake import IdeaLake
            lake = IdeaLake(str(lake_path))
        update_report(results_dir, ideas, cfg, lake=lake)
        print("Report updated.")
        return

    # --research-only is an alias for --role-only research
    if args.research_only:
        args.role_only = "research"

    # Detect GPUs
    if args.gpus:
        gpu_ids = [int(g.strip()) for g in args.gpus.split(",")]
    else:
        gpu_ids = detect_all_gpus()

    if not gpu_ids:
        logger.error("No GPUs detected. Use --gpus to specify manually.")
        sys.exit(1)

    # Launch orchestrator
    from orze.engine.orchestrator import Orze
    orze = Orze(gpu_ids, cfg, once=args.once)

    if args.role_only:
        orze._run_role_once(args.role_only)
    else:
        orze.run()


if __name__ == "__main__":
    main()
